## Numpy Tutorial

NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed.

In [1]:
#Importing Numpy package
import numpy as np


In [ ]:
np.info(np.ndarray.dtype) #For help

In [2]:
#Declaring simple array
a = np.array([2,3,4,6,2])  # we will call its as axis
a

array([2, 3, 4, 6, 2])

In [130]:
len(a)

5

In [3]:
#Initiating static two dimensional array
b = np.array([[2,3,4,6,2],[4,5,6,9,4]])
print(b)

[[2 3 4 6 2]
 [4 5 6 9 4]]


In [61]:
a = np.array([3,6,7])
print(a)
print("Size of Array : ", a.size)
print("Array Element type : ", a.dtype)
print("No of Dimension : ", a.ndim)
print("Shape of Array : ", a.shape)

[3 6 7]
Size of Array :  3
Array Element type :  int32
No of Dimension :  1
Shape of Array :  (3,)


In [132]:
a = np.array([ [31,62,7,6], [15,32,7,3],
             [65,12,17,23]])
print(a) 
print("Size of Array : ", a.size)
print("Array Element type : ", a.dtype.name)
print("No of Dimension : ", a.ndim)
print("Shape of Array : ", a.shape)

[[31 62  7  6]
 [15 32  7  3]
 [65 12 17 23]]
Size of Array :  12
Array Element type :  int32
No of Dimension :  2
Shape of Array :  (3, 4)


In [133]:
#a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True) convert an array into different type
a.astype(float)

array([[31., 62.,  7.,  6.],
       [15., 32.,  7.,  3.],
       [65., 12., 17., 23.]])

In [134]:
a[1][2]

7

In [135]:
a[1,3]

3

In [72]:
a = np.array([[ [ [ [31,62,7,6], [15,32,7,3],[65,12,17,23],[12,4,3,5]],
                [ [61,82,7,16], [75,2,17,23],[85,22,17,23],[22,23,44,2]]
              ]] ])
print(a) 
print("Size of Array : ", a.size)
print("Array Element type : ", a.dtype)
print("No of Dimension : ", a.ndim)
print("Shape of Array : ", a.shape)

[[[[[31 62  7  6]
    [15 32  7  3]
    [65 12 17 23]
    [12  4  3  5]]

   [[61 82  7 16]
    [75  2 17 23]
    [85 22 17 23]
    [22 23 44  2]]]]]
Size of Array :  32
Array Element type :  int32
No of Dimension :  5
Shape of Array :  (1, 1, 2, 4, 4)


In [80]:
a[0,0,1]

array([[61, 82,  7, 16],
       [75,  2, 17, 23],
       [85, 22, 17, 23],
       [22, 23, 44,  2]])

In [4]:
# ndim parameter to get dimension of array
b.ndim

2

In [5]:
#array shape parameter to get shape of the array
a.shape

(5,)

In [6]:
print(b)

[[2 3 4 6 2]
 [4 5 6 9 4]]


In [7]:
#dtype parameter to get type of array
type(b)
b.dtype

dtype('int32')

In [8]:
# auto type casting to higher data types as Array is homogenous
c = np.array([2,3,4.2,6,2])
c

array([2. , 3. , 4.2, 6. , 2. ])

In [9]:
#Checking auto typecasting
c.dtype


dtype('float64')

In [10]:
#string can be auto typecasted as well.
b = np.array([6, 7, 8.0,'a'])
print(b)
print(b.dtype)

['6' '7' '8.0' 'a']
<U32


In [13]:
# array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [14]:
b.ndim

2

In [15]:
#The type of the array can also be explicitly specified at creation time:
c = np.array( [ [1,2.2], [3,4] ], dtype=int )
c

array([[1, 2],
       [3, 4]])

In [23]:
#The function zeros creates an array full of zeros
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [113]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [115]:
### np.full(shape, fill_value, dtype=None, order='C')
e=np.full((2,2),3)
e

array([[3, 3],
       [3, 3]])

In [118]:
#np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
f = np.eye(4) # create a 4*4 identity matrix
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [122]:
#empty(shape, dtype=float, order='C')
np.empty((3,3)) # creates an empty array

array([[2.12199579e-314, 2.11562980e-311, 2.11987380e-311],
       [2.12411779e-311, 4.23762560e-311, 4.24186959e-311],
       [4.24611358e-311, 6.35962139e-311, 6.36386538e-311]])

In [124]:
## numpy.save(file, arr, allow_pickle=True, fix_imports=True)
a = np.arange(5) 
  
# a is printed. 
print("a is:") 
print(a) 
  
# the array is saved in the file geekfile.npy  
np.save('geekfile', a) 
  
print("the array is saved in the file geekfile.npy") 

a is:
[0 1 2 3 4]
the array is saved in the file geekfile.npy


In [125]:
# np.savez(file, *args, **kwds) Save several arrays into a single file in uncompressed .npz format.
np.savez('geekfile.npz',a,b)

In [127]:
np.load('geekfile.npy')

array([0, 1, 2, 3, 4])

In [ ]:
#saving and loading txt files
np.loadtxt("myfile.txt")

In [ ]:
np.genfromtxt("mtcars.csv",delimiter=',')

In [129]:
#Save an array to a text file.
np.savetxt("myarray.txt",a,delimiter=" ")

In [82]:
## np.arange( start, end,step )

In [24]:
#arange function to create sequential array
data = np.arange(30)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
## np.linspace(start, end,no of elements)

In [83]:
np.linspace(10,50,7)

array([10.        , 16.66666667, 23.33333333, 30.        , 36.66666667,
       43.33333333, 50.        ])

In [25]:
#reshape function to reshape array to the required dimension
data= data.reshape(6,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [198]:
#more reshape examples
data1 = np.arange(10,100,5).reshape(6,3)
data2 = np.arange(110,200,5).reshape(6,3)
data1

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50],
       [55, 60, 65],
       [70, 75, 80],
       [85, 90, 95]])

In [199]:
data3= np.arange(18).reshape(6,3)
data3**15

array([[          0,           1,       32768],
       [   14348907,  1073741824,   452807053],
       [ 2033549312,  1622647863,           0],
       [-1010140999, -1530494976,  1632031715],
       [-1073741824,  1788720133,  -769949696],
       [ 1500973039,           0,  2116147697]], dtype=int32)

In [200]:
#create 3-D with reshape for arange(24)
a = np.arange(24).reshape(2,3,4)
print(a)
print("shape :",a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
shape : (2, 3, 4)


In [201]:
#creating array for spliting examples
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [202]:
#horizontal splititing
a_hsplit = np.hsplit(a,2)
a_hsplit

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [203]:
#Vertical split
a_vsplit=np.vsplit(a,2)
a_vsplit

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [205]:
np.column_stack((a,a))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15],
       [16, 17, 18, 19, 16, 17, 18, 19],
       [20, 21, 22, 23, 20, 21, 22, 23]])

In [206]:
np.concatenate((a,a),axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
#creating arrays for stacking examples
a = np.arange(16).reshape(4,4)
b = np.arange(16,32).reshape(4,4)

In [32]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
b

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [34]:
#combing arrays with vertical stacking
np.vstack((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [35]:
#combing arrays with hozontal stacking
np.hstack((a,b))

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [36]:
#universal functions such as sqrt, sin, cos etc.,
print("Pi constant value : ",np.pi)  # pi constant
d = np.arange(0,120,30).reshape(2,2)  # array to apply sin cos
print("d array with angles in degrees")
print(d)
d_rad = d*np.pi/180 # converted angles to radians
print("d array with angles in radians")
print(d_rad)
print("Sin values of angles 0,30,60,90")
print(np.sin(d_rad))
print("Square root function on array")
e = np.array([4,9,16,25])
np.sqrt(e)

Pi constant value :  3.141592653589793
d array with angles in degrees
[[ 0 30]
 [60 90]]
d array with angles in radians
[[0.         0.52359878]
 [1.04719755 1.57079633]]
Sin values of angles 0,30,60,90
[[0.        0.5      ]
 [0.8660254 1.       ]]
Square root function on array


array([2., 3., 4., 5.])

In [138]:
a = np.arange(9).reshape(3,3)
b = np.arange(9,18).reshape(3,3)

In [140]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [141]:
b

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [139]:
a-b # similary substraction,multiplication,division,np.sqrt(a) etc..

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

In [142]:
np.subtract(a,b)

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

In [143]:
#comparison techniques
a==b

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [144]:
a<b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [145]:
#aggregate functions
a.sum() #arraywise sum

36

In [148]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [146]:
a.min() #arraywise min value

0

In [151]:
a.max()

8

In [149]:
a.max(axis=0)

array([6, 7, 8])

In [152]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [153]:
a.cumsum(axis = 1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [154]:
a.mean()

4.0

In [159]:
np.median(a)

4.0

In [158]:
np.corrcoef(a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [160]:
np.std(a)

2.581988897471611

In [161]:
#sorting array
a.sort()

In [162]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [164]:
b.sort(axis = 0)
b

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [179]:
#subsetting ,slicling and indexing
x = np.arange(9).reshape(3,3)
y = np.arange(9,18).reshape(3,3)

In [180]:
x[2]

array([6, 7, 8])

In [181]:
x[1,2]

5

In [182]:
#slicing
a[0:2]

array([[  0,   0,   2,   3],
       [  4, 160,   6,   7]])

In [183]:
a[0:2,1]

array([  0, 160])

In [184]:
a[:1]

array([[0, 0, 2, 3]])

In [186]:
a[1,...]

array([  4, 160,   6,   7])

In [187]:
a[: :-1]

array([[  8,   9,  10,  11],
       [  4, 160,   6,   7],
       [  0,   0,   2,   3]])

In [188]:
#boolean indexing
a[a<2]

array([0, 0])

In [191]:
#array manupulation
#transposing an array
i=np.transpose(a)
i.transpose
a

array([[  0,   0,   2,   3],
       [  4, 160,   6,   7],
       [  8,   9,  10,  11]])

In [192]:
#changing arrray shape
a.ravel()

array([  0,   0,   2,   3,   4, 160,   6,   7,   8,   9,  10,  11])

In [194]:
# Adding and removing elements
a.resize((2,6))
a

array([[  0,   0,   2,   3,   4, 160],
       [  6,   7,   8,   9,  10,  11]])

In [195]:
np.append(a,b)

array([  0,   0,   2,   3,   4, 160,   6,   7,   8,   9,  10,  11,   0,
         0,   2,   3,   4, 160,   6,   7,   8,   9,  10,  11])

In [196]:
np.insert(a,1,5)

array([  0,   5,   0,   2,   3,   4, 160,   6,   7,   8,   9,  10,  11])

In [197]:
np.delete(a,[1])

array([  0,   2,   3,   4, 160,   6,   7,   8,   9,  10,  11])

In [37]:
#Numpy is capable of  huge Arrays manuplation very efficiently
a = np.arange(9000000).reshape(9000,1000)
a


array([[      0,       1,       2, ...,     997,     998,     999],
       [   1000,    1001,    1002, ...,    1997,    1998,    1999],
       [   2000,    2001,    2002, ...,    2997,    2998,    2999],
       ...,
       [8997000, 8997001, 8997002, ..., 8997997, 8997998, 8997999],
       [8998000, 8998001, 8998002, ..., 8998997, 8998998, 8998999],
       [8999000, 8999001, 8999002, ..., 8999997, 8999998, 8999999]])

In [38]:
#shape manuplation
a = np.arange(4).reshape(2,2)
b = np.arange(11,15).reshape(2,2)
print(a)
print(b)


[[0 1]
 [2 3]]
[[11 12]
 [13 14]]


In [88]:
#Generating random number with Numpy. random number are between 0 and 1
np.random.random()

0.6952124136571721

In [89]:
int(np.random.rand()*100)

84

In [90]:
# min + (max-min)*rand()
int(35 + (100-35)*np.random.rand())

51

In [91]:
np.sqrt(np.random.randint(35,100,100000000).reshape(100000,1000))

array([[8.71779789, 9.        , 7.61577311, ..., 7.93725393, 9.94987437,
        8.77496439],
       [9.53939201, 9.89949494, 8.88819442, ..., 8.42614977, 7.34846923,
        9.79795897],
       [8.1240384 , 7.14142843, 7.61577311, ..., 9.53939201, 6.32455532,
        8.66025404],
       ...,
       [9.79795897, 8.71779789, 6.32455532, ..., 6.92820323, 8.60232527,
        9.16515139],
       [7.68114575, 6.        , 7.61577311, ..., 9.48683298, 6.244998  ,
        6.244998  ],
       [9.38083152, 9.74679434, 6.63324958, ..., 7.74596669, 8.1240384 ,
        8.94427191]])

In [92]:
a = np.random.randint(1,10,4).reshape(2,2)
b = np.random.randint(1,10,4).reshape(2,2)
print(a)
print(b)

[[7 1]
 [8 9]]
[[3 2]
 [1 4]]


In [93]:
np.matmul(a,b)

array([[22, 18],
       [33, 52]])

#### Random number functions in numpy.random
rand(d0, d1, …, dn)	Random values in a given shape. <br\>
randn(d0, d1, …, dn)	Return a sample (or samples) from the “standard normal” distribution.<br\>
randint(low[, high, size, dtype])	Return random integers from low (inclusive) to high (exclusive).<br\>
random_integers(low[, high, size])	Random integers of type np.int between low and high, inclusive.<br\>
random_sample([size])	Return random floats in the half-open interval [0.0, 1.0).<br\>
random([size])	Return random floats in the half-open interval [0.0, 1.0).<br\>
ranf([size])	Return random floats in the half-open interval [0.0, 1.0).<br\>
sample([size])	Return random floats in the half-open interval [0.0, 1.0).<br\>
choice(a[, size, replace, p])	Generates a random sample from a given 1-D array<br\>
bytes(length)	Return random bytes.


In [51]:
print("Random numbers with required shape")
print(np.random.rand(3,2))
print("random integers betweet two numbers with required size")
print(np.random.randint(10,50,10)) # low,high,size

Random numbers with required shape
[[0.64418325 0.19470508]
 [0.43894034 0.39409427]
 [0.97126886 0.73130121]]
random integers betweet two numbers with required size
[15 43 28 42 47 48 36 17 34 32]


In [41]:
#Numpy floor, ceil and round
print(np.floor(5.9))
print(np.ceil(3.3))
print(np.round(4.7))


5.0
4.0
5.0


In [167]:
#Copies and Views

# No Copy at All¶

a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [168]:
b = a            # no new object is created
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [169]:
a[5] = 160
a

array([  0,   1,   2,   3,   4, 160,   6,   7,   8,   9,  10,  11])

In [170]:
b

array([  0,   1,   2,   3,   4, 160,   6,   7,   8,   9,  10,  11])

In [171]:
b.shape = 3,4    # changes the shape of a.shape(3, 4)

In [172]:
b

array([[  0,   1,   2,   3],
       [  4, 160,   6,   7],
       [  8,   9,  10,  11]])

In [173]:
a.shape

(3, 4)

In [174]:
h= a.view()  #creates a view of the array with the same data

In [175]:
h

array([[  0,   1,   2,   3],
       [  4, 160,   6,   7],
       [  8,   9,  10,  11]])

In [176]:
a[0][1]= 0

In [177]:
a

array([[  0,   0,   2,   3],
       [  4, 160,   6,   7],
       [  8,   9,  10,  11]])

In [178]:
h

array([[  0,   0,   2,   3],
       [  4, 160,   6,   7],
       [  8,   9,  10,  11]])

In [212]:
c.base is a  
a.shape
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [210]:
           # a's shape doesn't change
c

array([[1, 2],
       [3, 4]])

In [ ]:
c[0,4] = 999                    # a's data changes
c

In [ ]:
a

In [59]:
# Deep Copy

b = a.copy() 


In [61]:
a[4] = 234
a

array([  0,   1,   2,   3, 234, 160,   6,   7,   8,   9,  10,  11])

In [62]:
b

array([  0,   1,   2,   3,   4, 160,   6,   7,   8,   9,  10,  11])

## This completes basic tutorial on Numpy package